In [5]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
list(iris.keys())


['data', 'target', 'target_names', 'DESCR', 'feature_names']

In [21]:
X = iris["data"][:, (2, 3)]
y = iris["target"]

In [24]:
# add bias term for every instance X0 =1
X_b = np.c_[np.ones([len(X), 1]), X]
print(X_b)
# random seed so output is reproducible
np.random.seed(2042)


[[ 1.   1.4  0.2]
 [ 1.   1.4  0.2]
 [ 1.   1.3  0.2]
 [ 1.   1.5  0.2]
 [ 1.   1.4  0.2]
 [ 1.   1.7  0.4]
 [ 1.   1.4  0.3]
 [ 1.   1.5  0.2]
 [ 1.   1.4  0.2]
 [ 1.   1.5  0.1]
 [ 1.   1.5  0.2]
 [ 1.   1.6  0.2]
 [ 1.   1.4  0.1]
 [ 1.   1.1  0.1]
 [ 1.   1.2  0.2]
 [ 1.   1.5  0.4]
 [ 1.   1.3  0.4]
 [ 1.   1.4  0.3]
 [ 1.   1.7  0.3]
 [ 1.   1.5  0.3]
 [ 1.   1.7  0.2]
 [ 1.   1.5  0.4]
 [ 1.   1.   0.2]
 [ 1.   1.7  0.5]
 [ 1.   1.9  0.2]
 [ 1.   1.6  0.2]
 [ 1.   1.6  0.4]
 [ 1.   1.5  0.2]
 [ 1.   1.4  0.2]
 [ 1.   1.6  0.2]
 [ 1.   1.6  0.2]
 [ 1.   1.5  0.4]
 [ 1.   1.5  0.1]
 [ 1.   1.4  0.2]
 [ 1.   1.5  0.1]
 [ 1.   1.2  0.2]
 [ 1.   1.3  0.2]
 [ 1.   1.5  0.1]
 [ 1.   1.3  0.2]
 [ 1.   1.5  0.2]
 [ 1.   1.3  0.3]
 [ 1.   1.3  0.3]
 [ 1.   1.3  0.2]
 [ 1.   1.6  0.6]
 [ 1.   1.9  0.4]
 [ 1.   1.4  0.3]
 [ 1.   1.6  0.2]
 [ 1.   1.4  0.2]
 [ 1.   1.5  0.2]
 [ 1.   1.4  0.2]
 [ 1.   4.7  1.4]
 [ 1.   4.5  1.5]
 [ 1.   4.9  1.5]
 [ 1.   4.   1.3]
 [ 1.   4.6  1.5]
 [ 1.   4.

In [30]:
# create train, test, validation sets
test_ratio = 0.2
validation_ratio = 0.2
total_size = len(X_b)
test_size = total_size * test_ratio
validation_size = total_size * validation_ratio
train_size = total_size - test_size - validation_size
rnd_indices = np.random.permutation(total_size)
print(rnd_indices)
X_train = X_b[rnd_indices[:int(train_size)]]
y_train = y[rnd_indices[:int(train_size)]]
X_test = X_b[rnd_indices[int(train_size):-int(test_size)]]
y_test = y[rnd_indices[int(train_size):-int(test_size)]]
X_validation = X_b[rnd_indices[-int(test_size)]:]
y_validation = y[rnd_indices[-int(test_size)]:]


[ 60 134  98   5  76  24  17 143  91  41  16  66  61 128  73  96  28  44
 133 106  95 129  88  23  70  52  18 113  72 107 118  80 137  36  19 122
 108  83  45  77  21  64   0  85  29  55 119  56  32  84  31  79   2   7
  30 123   3  40  81  74 109 116  37  59  69  26   9  78 105  13 136  65
 102  27   8  33 146  43  46  94 141 147 111  10  97  42 114  12  48  50
  86 104  62 144  75  35 131  67  11  14  90  49 130  15  71 132 121  20
  53 139  51  47 145  22 115  99  93  38   1 149 117 101  58 103 100 126
 112  25  89  39 140 138  63 135 142  82 120  54  57  34  68   4  87  92
 127 125 110 124   6 148]


In [43]:
# turn classes to one hot
def to_one_hot(y):
    n_classes = y.max() + 1
    m = len(y)
    Y_one_hot = np.zeros((m, n_classes))
    Y_one_hot[np.arange(m), y] = 1
    return Y_one_hot


In [44]:
y_train[:10]

array([1, 2, 1, 0, 1, 0, 0, 2, 1, 0])

In [45]:
to_one_hot(y_train)

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.

In [47]:
Y_train_one_hot = to_one_hot(y_train)
Y_valid_one_hot = to_one_hot(y_validation)
Y_test_one_hot = to_one_hot(y_test)

In [56]:
def softmax(logits):
    exps = np.exp(logits)
    exp_sums = np.sum(exps, axis=1, keepdims=True)
    return exps / exp_sums

In [57]:
n_inputs = X_train.shape[1] # == 3 (2 features plus the bias term)
n_outputs = len(np.unique(y_train))   # == 3 (3 iris classes)

In [84]:
eta = 0.01
n_iterations = 5001
m = len(X_train)
epsilon = 1e-7
alpha = 0.1  # regularization hyperparameter
Theta = np.random.randn(n_inputs, n_outputs)
best_loss = np.infty
for i in range(n_iterations):
    logits = X_train.dot(Theta)
    Y_proba =softmax(logits)
    xentropy_loss = -np.mean(np.sum(Y_train_one_hot * np.log(Y_proba + epsilon), axis=1))
    # Note that the bias term θ0 is not regularized
    l2_loss = 1/2 * np.sum(np.square(Theta[1:])) 
    error = Y_proba - Y_train_one_hot
    loss = xentropy_loss + alpha * l2_loss
    if i % 500 == 0:
        print(i, loss)
        print('error' + str(error))
        print(error.shape)
    gradients = 1/m * X_train.T.dot(error)
    print(gradients.shape)
    Theta = Theta - eta * gradients
    if loss < best_loss:
        best_loss = loss
    else:
        print(i - 1, best_loss)
        print(i, loss, "early stopping!")
        break

0 2.4309632637
error[[ 0.05569977 -0.11554976  0.05984999]
 [ 0.00557563  0.99021826 -0.99579389]
 [ 0.12767785 -0.23364215  0.1059643 ]
 [-0.85007829  0.50757938  0.34249891]
 [ 0.01867447 -0.03101307  0.0123386 ]
 [-0.91132187  0.61389841  0.29742346]
 [-0.83890152  0.42156783  0.41733369]
 [ 0.02166733  0.97479018 -0.99645751]
 [ 0.02513339 -0.04119822  0.01606484]
 [-0.82734085  0.38740899  0.43993187]
 [-0.79871301  0.36835915  0.43035386]
 [ 0.03545372 -0.05415645  0.01870273]
 [ 0.05458585 -0.08198486  0.02739901]
 [ 0.02280191  0.9721601  -0.99496201]
 [ 0.0145334  -0.02794747  0.01341407]
 [ 0.03704348 -0.06345164  0.02640816]
 [-0.86293448  0.43977304  0.42316143]
 [-0.87447456  0.57804687  0.29642769]
 [ 0.01455282  0.97696774 -0.99152056]
 [ 0.05230736  0.92826436 -0.98057172]
 [ 0.03044302 -0.05630728  0.02586426]
 [ 0.00616387  0.9904519  -0.99661576]
 [ 0.04277279 -0.07276427  0.02999148]
 [-0.82388943  0.4862958   0.33759363]
 [ 0.04117333 -0.05465955  0.01348622]
 [ 0.

(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)

(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)

(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)

In [85]:
Theta

array([[ 4.12579447, -0.46146947, -1.82295444],
       [-0.75397443,  1.03253511,  0.67319427],
       [-0.01926772, -0.45815783,  1.45265545]])

In [86]:
# predictions for validation set
logits = X_validation.dot(Theta)
Y_proba = softmax(logits)
y_pred = np.argmax(Y_proba, axis=1)
print(y_pred)
accuracy_score = np.mean(y_pred == y_validation)
accuracy_score

[2 2 1 2 2 2 2 2 1 2 2 2 1 2 2 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


0.84848484848484851