In [61]:
'''
1. What is the approximate depth of a Decision Tree trained (without restrictions) on a training set with 1 million instances?
Depth of a Decision Tree is N-1 where N is the number of training samples. You can derive this by considering that the least effective split would be peeling off one training example per node.
'''

'\n1. What is the approximate depth of a Decision Tree trained (without restrictions) on a training set with 1 million instances?\nDepth of a Decision Tree is N-1 where N is the number of training samples. You can derive this by considering that the least effective split would be peeling off one training example per node.\n'

In [62]:
'''
2. Is a node’s Gini impurity generally lower or greater than its parent’s? Is it generally lower/greater, or always lower/greater?
Generally a nodes Gini umpurity is lower than its parents because the CART traning algorithm uses
a cost function that produces the purest subsets weighted by their size.
'''

'\n2. Is a node’s Gini impurity generally lower or greater than its parent’s? Is it generally lower/greater, or always lower/greater?\nGenerally a nodes Gini umpurity is lower than its parents because the CART traning algorithm uses\na cost function that produces the purest subsets weighted by their size.\n'

In [63]:
'''
3. If a Decision Tree is overfitting the training set, is it a good idea to try decreasing max_depth?
Yes.
'''

'\n3. If a Decision Tree is overfitting the training set, is it a good idea to try decreasing max_depth?\nYes.\n'

In [64]:
'''
4. If a Decision Tree is underfitting the training set, is it a good idea to try scaling the input features?
No, Decision Trees don't require feature scaling.
'''

"\n4. If a Decision Tree is underfitting the training set, is it a good idea to try scaling the input features?\nNo, Decision Trees don't require feature scaling.\n"

In [65]:
'''
5. If it takes one hour to train a Decision Tree on a training set containing 1 million instances, roughly how much time will it take to train another Decision Tree on a training set containing 10 million instances?
The training complexity is O(n*mlog(m)) where m is the number of samples. So 10,000,000 will take ~11.7 hours to train.
'''

'\n5. If it takes one hour to train a Decision Tree on a training set containing 1 million instances, roughly how much time will it take to train another Decision Tree on a training set containing 10 million instances?\nThe training complexity is O(n*mlog(m)) where m is the number of samples. So 10,000,000 will take ~11.7 hours to train.\n'

In [66]:
'''
6. If your training set contains 100,000 instances, will setting presort=True speed up training?
No, presort will only help if training sets have less than a few thousand instances.
'''

'\n6. If your training set contains 100,000 instances, will setting presort=True speed up training?\nNo, presort will only help if training sets have less than a few thousand instances.\n'

In [67]:
# 7
import numpy as np
from sklearn.datasets import make_moons
moons_data = make_moons(n_samples=10000, noise=0.4)
print(moons_data)

(array([[-0.00629982,  0.19298109],
       [ 1.00077558, -0.12432866],
       [-1.85519594, -0.32988076],
       ..., 
       [-0.50473235, -0.22363531],
       [-0.88224129,  0.307626  ],
       [-0.81146457,  1.08205398]]), array([0, 0, 0, ..., 0, 0, 0], dtype=int64))


In [68]:
from sklearn.model_selection import train_test_split
X = moons_data[0]
y = moons_data[1]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 0.62596106  0.10727495]
 [ 0.17685224  0.71787486]
 [ 1.76932921 -0.2541071 ]
 ..., 
 [ 0.11746472  0.22361804]
 [ 1.06325571  0.47634452]
 [ 0.71017107  0.16983526]]
[0 0 1 ..., 1 1 0]
[[ 0.27165539  0.15381178]
 [-0.71113266  0.43008922]
 [-0.73240298  0.68191689]
 ..., 
 [-0.10878564  1.0767956 ]
 [-0.63085077  0.55958764]
 [ 0.58092708  1.11959262]]
[1 0 0 ..., 0 0 0]


In [69]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
tree_clf = DecisionTreeClassifier()
params = {'max_depth':[1, 2, 4, 8, 16, 32], 'max_leaf_nodes':[2, 4, 8, 16, 32, 64, 128]}
clf = GridSearchCV(tree_clf, params, cv=5)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'max_depth': [1, 2, 4, 8, 16, 32], 'max_leaf_nodes': [2, 4, 8, 16, 32, 64, 128]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [70]:
print(clf.best_params_)

{'max_depth': 8, 'max_leaf_nodes': 32}


In [71]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
# accuracy
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

             precision    recall  f1-score   support

          0       0.84      0.89      0.86      1655
          1       0.88      0.83      0.85      1645

avg / total       0.86      0.86      0.86      3300

0.857575757576


In [72]:
# 8
from sklearn.model_selection import ShuffleSplit
rs = ShuffleSplit(n_splits=1000, train_size=.01, random_state=0)

n_trees = 1000
mini_sets = []

tree_clf = DecisionTreeClassifier(max_depth=16, max_leaf_nodes=32)
for train_index, test_index in rs.split(X):
    X_mini_train = X[train_index]
    y_mini_train = y[train_index]
    mini_sets.append((X_mini_train, y_mini_train))
    

C:\Users\quanu\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1639: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [73]:
from sklearn.base import clone
forest = [clone(clf.best_estimator_) for _ in range(n_trees)]

In [74]:
accuracy_scores = []

for tree, (X_mini_train, y_mini_train) in zip(forest, mini_sets):
    tree.fit(X_mini_train, y_mini_train)
    
    y_pred = tree.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))

np.mean(accuracy_scores)

0.79429939393939386

In [75]:
Y_pred = np.empty([n_trees, len(X_test)], dtype=np.uint8)
print(Y_pred)
for tree_index, tree in enumerate(forest):
    Y_pred[tree_index] = tree.predict(X_test)


[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [76]:
from scipy.stats import mode

y_pred_majority_votes, n_votes = mode(Y_pred, axis=0)

In [77]:
accuracy_score(y_test, y_pred_majority_votes.reshape([-1]))

0.86848484848484853