In [44]:
'''
1. What are the main benefits of creating a computation graph rather than directly executing the computations? What are the main drawbacks?
The benefits of creating a computational graph is perforance, modularity, visualization, and ability to run on GPUs.
Some drawbacks include: a steep learning curve, and is overkill for simpler machine learning tasks.
'''

'\n1. What are the main benefits of creating a computation graph rather than directly executing the computations? What are the main drawbacks?\nThe benefits of creating a computational graph is perforance, modularity, visualization, and ability to run on GPUs.\nSome drawbacks include: a steep learning curve, and is overkill for simpler machine learning tasks.\n'

In [45]:
'''
2. Is the statement a_val = a.eval(session=sess) equivalent to a_val = sess.run(a)?
Yes.
'''

'\n2. Is the statement a_val = a.eval(session=sess) equivalent to a_val = sess.run(a)?\nYes.\n'

In [46]:
'''
3. Is the statement a_val, b_val = a.eval(session=sess), b.eval(session=sess) equivalent to a_val, b_val = sess.run([a, b])?
Yes.
'''

'\n3. Is the statement a_val, b_val = a.eval(session=sess), b.eval(session=sess) equivalent to a_val, b_val = sess.run([a, b])?\nYes.\n'

In [47]:
'''
4. Can you run two graphs in the same session?
No, each session can only have a single graph.
'''

'\n4. Can you run two graphs in the same session?\nNo, each session can only have a single graph.\n'

In [48]:
'''
5. If you create a graph g containing a variable w, then start two threads and open a session in each thread, both using the same graph g, will each session have its own copy of the variable w or will it be shared?
Each session will have its own copy of w.
'''

'\n5. If you create a graph g containing a variable w, then start two threads and open a session in each thread, both using the same graph g, will each session have its own copy of the variable w or will it be shared?\nEach session will have its own copy of w.\n'

In [49]:
'''
6. When is a variable initialized? When is it destroyed?
A variable is initialize when a session is made and initializes the variable.
A variable is destroyed when the session is closed.
'''

'\n6. When is a variable initialized? When is it destroyed?\nA variable is initialize when a session is made and initializes the variable.\nA variable is destroyed when the session is closed.\n'

In [50]:
'''
7. What is the difference between a placeholder and a variable?
Variables are usually trainable and used for weights and biases in the model.
Placeholder is used to feed training data. Placeholders are input data and will
not be trained over time.
'''

'\n7. What is the difference between a placeholder and a variable?\nVariables are usually trainable and used for weights and biases in the model.\nPlaceholder is used to feed training data. Placeholders are input data and will\nnot be trained over time.\n'

In [51]:
'''
8. What happens when you run the graph to evaluate an operation that depends on a placeholder but you don’t feed its value? What happens if the operation does not depend on the placeholder?
If no data is passed at runtime then you get an exception.
If the operation doesn't depend on the placeholder then don't supply a feed_dict.
Not sure what happens...?
'''

"\n8. What happens when you run the graph to evaluate an operation that depends on a placeholder but you don’t feed its value? What happens if the operation does not depend on the placeholder?\nIf no data is passed at runtime then you get an exception.\nIf the operation doesn't depend on the placeholder then don't supply a feed_dict.\nNot sure what happens...?\n"

In [52]:
'''
9. When you run a graph, can you feed the output value of any operation, or just the value of placeholders?
You can actually feed the output of any operations, not just placeholders.
'''

'\n9. When you run a graph, can you feed the output value of any operation, or just the value of placeholders?\nYou can actually feed the output of any operations, not just placeholders.\n'

In [53]:
'''
10. How can you set a variable to any value you want (during the execution phase)?
IDK.
'''

'\n10. How can you set a variable to any value you want (during the execution phase)?\nIDK.\n'

In [54]:
'''
11. How many times does reverse-mode autodiff need to traverse the graph in order to compute the gradients of the cost function with regards to 10 variables? What about forward-mode autodiff? And symbolic differentiation?
noutputs + 1, ninputs, and N/A.
'''

'\n11. How many times does reverse-mode autodiff need to traverse the graph in order to compute the gradients of the cost function with regards to 10 variables? What about forward-mode autodiff? And symbolic differentiation?\nnoutputs + 1, ninputs, and N/A.\n'

In [55]:
'''
12. Implement Logistic Regression with Mini-batch Gradient Descent using TensorFlow. Train it and evaluate it on the moons dataset (introduced in Chapter 5). Try adding all the bells and whistles:

Define the graph within a logistic_regression() function that can be reused easily.

Save checkpoints using a Saver at regular intervals during training, and save the final model at the end of training.

Restore the last checkpoint upon startup if training was interrupted.

Define the graph using name scopes so the graph looks good in TensorBoard.

Add summaries to visualize the learning curves in TensorBoard.

Try tweaking some hyperparameters such as the learning rate or the mini-batch size and look at the shape of the learning curve.
'''

'\n12. Implement Logistic Regression with Mini-batch Gradient Descent using TensorFlow. Train it and evaluate it on the moons dataset (introduced in Chapter 5). Try adding all the bells and whistles:\n\nDefine the graph within a logistic_regression() function that can be reused easily.\n\nSave checkpoints using a Saver at regular intervals during training, and save the final model at the end of training.\n\nRestore the last checkpoint upon startup if training was interrupted.\n\nDefine the graph using name scopes so the graph looks good in TensorBoard.\n\nAdd summaries to visualize the learning curves in TensorBoard.\n\nTry tweaking some hyperparameters such as the learning rate or the mini-batch size and look at the shape of the learning curve.\n'

In [56]:
# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [57]:
from sklearn.datasets import make_moons
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
moons_data = make_moons(n_samples=1000, noise=0.1)
from sklearn.model_selection import train_test_split

n_samples = 1000
X_moons, y_moons = make_moons(n_samples, noise=0.1, random_state=42)
X_moons_with_bias = np.c_[np.ones((n_samples, 1)), X_moons]
y_moons_column_vector = y_moons.reshape(-1, 1)

print(y_moons_column_vector)

test_ratio = 0.2
test_size = int(n_samples * test_ratio)
X_train = X_moons_with_bias[:-test_size]
X_test = X_moons_with_bias[-test_size:]
y_train = y_moons_column_vector[:-test_size]
y_test = y_moons_column_vector[-test_size:]



[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]


In [58]:
def random_batch(X_train, y_train, batch_size):
    rnd_indices = np.random.randint(0, len(X_train), batch_size)
    X_batch = X_train[rnd_indices]
    y_batch = y_train[rnd_indices]
    return X_batch, y_batch

In [59]:
X_batch, y_batch = random_batch(X_train, y_train, 5)
print(X_batch)
print(y_batch)

[[ 1.          0.94220676 -0.46597098]
 [ 1.         -0.97372595  0.18078585]
 [ 1.          2.05730518  0.2083696 ]
 [ 1.         -0.00554437  0.15868281]
 [ 1.          0.10021403  1.05137369]]
[[1]
 [0]
 [1]
 [1]
 [0]]


In [60]:
reset_graph()

In [61]:
n_inputs  = 2

X = tf.placeholder(tf.float32, shape=(None, n_inputs + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")
theta = tf.Variable(tf.random_uniform([n_inputs + 1, 1], -1.0, 1.0, seed=42), name="theta")
logits = tf.matmul(X, theta, name="logits")
y_proba = 1 / (1 + tf.exp(-logits))

In [62]:
loss = tf.losses.log_loss(y, y_proba) 

In [63]:
learning_rate = 0.01
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

In [64]:
init = tf.global_variables_initializer()

In [65]:
n_epochs = 1000
batch_size = 50
n_batches = int(np.ceil(n_samples / batch_size))

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = random_batch(X_train, y_train, batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        loss_val = loss.eval({X: X_test, y: y_test})
        if epoch % 100 == 0:
            print("Epoch:", epoch, "\tLoss:", loss_val)

    y_proba_val = y_proba.eval(feed_dict={X: X_test, y: y_test})

Epoch: 0 	Loss: 0.79260236
Epoch: 100 	Loss: 0.3434635
Epoch: 200 	Loss: 0.30754045
Epoch: 300 	Loss: 0.29288894
Epoch: 400 	Loss: 0.28533572
Epoch: 500 	Loss: 0.28047806
Epoch: 600 	Loss: 0.27808294
Epoch: 700 	Loss: 0.2761544
Epoch: 800 	Loss: 0.27551997
Epoch: 900 	Loss: 0.27491233


In [66]:
y_pred = (y_proba_val >= 0.5)

In [67]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_test, y_pred)

0.8627450980392157

In [68]:
recall_score(y_test, y_pred)

0.8888888888888888

In [69]:
X_train_enhanced = np.c_[X_train,
                         np.square(X_train[:, 1]),
                         np.square(X_train[:, 2]),
                         X_train[:, 1] ** 3,
                         X_train[:, 2] ** 3]
X_test_enhanced = np.c_[X_test,
                        np.square(X_test[:, 1]),
                        np.square(X_test[:, 2]),
                        X_test[:, 1] ** 3,
                        X_test[:, 2] ** 3]

In [70]:
reset_graph()

In [71]:
def logistic_regression(X, y, initializer=None, seed=42, learning_rate=0.01):
    n_inputs_including_bias = int(X.get_shape()[1])
    with tf.name_scope("logistic_regression"):
        with tf.name_scope("model"):
            if initializer is None:
                initializer = tf.random_uniform([n_inputs_including_bias, 1], -1.0, 1.0, seed=seed)
            theta = tf.Variable(initializer, name="theta")
            logits = tf.matmul(X, theta, name="logits")
            y_proba = tf.sigmoid(logits)
        with tf.name_scope("train"):
            loss = tf.losses.log_loss(y, y_proba, scope="loss")
            optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
            training_op = optimizer.minimize(loss)
            loss_summary = tf.summary.scalar('log_loss', loss)
        with tf.name_scope("init"):
            init = tf.global_variables_initializer()
        with tf.name_scope("save"):
            saver = tf.train.Saver()
    return y_proba, loss, training_op, loss_summary, init, saver

In [72]:
from datetime import datetime

def log_dir(prefix=""):
    now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    root_logdir = "tf_logs"
    if prefix:
        prefix += "-"
    name = prefix + "run-" + now
    return "{}/{}/".format(root_logdir, name)

In [73]:
n_inputs = 2 + 4
logdir = log_dir("logreg")

X = tf.placeholder(tf.float32, shape=(None, n_inputs + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

y_proba, loss, training_op, loss_summary, init, saver = logistic_regression(X, y)

file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [77]:
import os
n_epochs = 10001
batch_size = 50
n_batches = int(np.ceil(n_samples / batch_size))

checkpoint_path = "/tmp/my_logreg_model.ckpt"
checkpoint_epoch_path = checkpoint_path + ".epoch"
final_model_path = "./my_logreg_model"

with tf.Session() as sess:
    if os.path.isfile(checkpoint_epoch_path):
        # if the checkpoint file exists, restore the model and load the epoch number
        with open(checkpoint_epoch_path, "rb") as f:
            start_epoch = int(f.read())
        print("Training was interrupted. Continuing at epoch", start_epoch)
        saver.restore(sess, checkpoint_path)
    else:
        start_epoch = 0
        sess.run(init)

    for epoch in range(start_epoch, n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = random_batch(X_train_enhanced, y_train, batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        loss_val, summary_str = sess.run([loss, loss_summary], feed_dict={X: X_test_enhanced, y: y_test})
        file_writer.add_summary(summary_str, epoch)
        if epoch % 500 == 0:
            print("Epoch:", epoch, "\tLoss:", loss_val)
            saver.save(sess, checkpoint_path)
            with open(checkpoint_epoch_path, "wb") as f:
                f.write(b"%d" % (epoch + 1))

    saver.save(sess, final_model_path)
    y_proba_val = y_proba.eval(feed_dict={X: X_test_enhanced, y: y_test})
    os.remove(checkpoint_epoch_path)

Training was interrupted. Continuing at epoch 3001
INFO:tensorflow:Restoring parameters from /tmp/my_logreg_model.ckpt
Epoch: 3500 	Loss: 0.062214404
Epoch: 4000 	Loss: 0.058002472
Epoch: 4500 	Loss: 0.054581195
Epoch: 5000 	Loss: 0.05167185
Epoch: 5500 	Loss: 0.04923751
Epoch: 6000 	Loss: 0.04719448
Epoch: 6500 	Loss: 0.04538568
Epoch: 7000 	Loss: 0.04379695
Epoch: 7500 	Loss: 0.042368747
Epoch: 8000 	Loss: 0.041095916
Epoch: 8500 	Loss: 0.03996932
Epoch: 9000 	Loss: 0.038926326
Epoch: 9500 	Loss: 0.03798957
Epoch: 10000 	Loss: 0.037133846


In [78]:
y_pred = (y_proba_val >= 0.5)

In [79]:
precision_score(y_test, y_pred)

0.9797979797979798

In [80]:
recall_score(y_test, y_pred)

0.9797979797979798