In [1]:
'''
1. What are the main benefits of creating a computation graph rather than directly executing the computations? What are the main drawbacks?
The benefits of creating a computational graph is perforance, modularity, visualization, and ability to run on GPUs.
Some drawbacks include: a steep learning curve, and is overkill for simpler machine learning tasks.
'''

'\n1. What are the main benefits of creating a computation graph rather than directly executing the computations? What are the main drawbacks?\nThe benefits of creating a computational graph is perforance, modularity, visualization, and ability to run on GPUs.\nSome drawbacks include: a steep learning curve, and is overkill for simpler machine learning tasks.\n'

In [2]:
'''
2. Is the statement a_val = a.eval(session=sess) equivalent to a_val = sess.run(a)?
Yes.
'''

'\n2. Is the statement a_val = a.eval(session=sess) equivalent to a_val = sess.run(a)?\nYes.\n'

In [3]:
'''
3. Is the statement a_val, b_val = a.eval(session=sess), b.eval(session=sess) equivalent to a_val, b_val = sess.run([a, b])?
Yes.
'''

'\n3. Is the statement a_val, b_val = a.eval(session=sess), b.eval(session=sess) equivalent to a_val, b_val = sess.run([a, b])?\nYes.\n'

In [4]:
'''
4. Can you run two graphs in the same session?
No, each session can only have a single graph.
'''

'\n4. Can you run two graphs in the same session?\nNo, each session can only have a single graph.\n'

In [5]:
'''
5. If you create a graph g containing a variable w, then start two threads and open a session in each thread, both using the same graph g, will each session have its own copy of the variable w or will it be shared?
Each session will have its own copy of w.
'''

'\n5. If you create a graph g containing a variable w, then start two threads and open a session in each thread, both using the same graph g, will each session have its own copy of the variable w or will it be shared?\nEach session will have its own copy of w.\n'

In [6]:
'''
6. When is a variable initialized? When is it destroyed?
A variable is initialize when a session is made and initializes the variable.
A variable is destroyed when the session is closed.
'''

'\n6. When is a variable initialized? When is it destroyed?\nA variable is initialize when a session is made and initializes the variable.\nA variable is destroyed when the session is closed.\n'

In [7]:
'''
7. What is the difference between a placeholder and a variable?
Variables are usually trainable and used for weights and biases in the model.
Placeholder is used to feed training data. Placeholders are input data and will
not be trained over time.
'''

'\n7. What is the difference between a placeholder and a variable?\nVariables are usually trainable and used for weights and biases in the model.\nPlaceholder is used to feed training data. Placeholders are input data and will\nnot be trained over time.\n'

In [8]:
'''
8. What happens when you run the graph to evaluate an operation that depends on a placeholder but you don’t feed its value? What happens if the operation does not depend on the placeholder?
If no data is passed at runtime then you get an exception.
If the operation doesn't depend on the placeholder then don't supply a feed_dict.
Not sure what happens...?
'''

"\n8. What happens when you run the graph to evaluate an operation that depends on a placeholder but you don’t feed its value? What happens if the operation does not depend on the placeholder?\nIf no data is passed at runtime then you get an exception.\nIf the operation doesn't depend on the placeholder then don't supply a feed_dict.\nNot sure what happens...?\n"

In [9]:
'''
9. When you run a graph, can you feed the output value of any operation, or just the value of placeholders?
You can actually feed the output of any operations, not just placeholders.
'''

'\n9. When you run a graph, can you feed the output value of any operation, or just the value of placeholders?\nYou can actually feed the output of any operations, not just placeholders.\n'

In [10]:
'''
10. How can you set a variable to any value you want (during the execution phase)?
IDK.
'''

'\n10. How can you set a variable to any value you want (during the execution phase)?\nIDK.\n'

In [11]:
'''
11. How many times does reverse-mode autodiff need to traverse the graph in order to compute the gradients of the cost function with regards to 10 variables? What about forward-mode autodiff? And symbolic differentiation?
noutputs + 1, ninputs, and N/A.
'''

'\n11. How many times does reverse-mode autodiff need to traverse the graph in order to compute the gradients of the cost function with regards to 10 variables? What about forward-mode autodiff? And symbolic differentiation?\nnoutputs + 1, ninputs, and N/A.\n'

In [12]:
'''
12. Implement Logistic Regression with Mini-batch Gradient Descent using TensorFlow. Train it and evaluate it on the moons dataset (introduced in Chapter 5). Try adding all the bells and whistles:

Define the graph within a logistic_regression() function that can be reused easily.

Save checkpoints using a Saver at regular intervals during training, and save the final model at the end of training.

Restore the last checkpoint upon startup if training was interrupted.

Define the graph using name scopes so the graph looks good in TensorBoard.

Add summaries to visualize the learning curves in TensorBoard.

Try tweaking some hyperparameters such as the learning rate or the mini-batch size and look at the shape of the learning curve.
'''

'\n12. Implement Logistic Regression with Mini-batch Gradient Descent using TensorFlow. Train it and evaluate it on the moons dataset (introduced in Chapter 5). Try adding all the bells and whistles:\n\nDefine the graph within a logistic_regression() function that can be reused easily.\n\nSave checkpoints using a Saver at regular intervals during training, and save the final model at the end of training.\n\nRestore the last checkpoint upon startup if training was interrupted.\n\nDefine the graph using name scopes so the graph looks good in TensorBoard.\n\nAdd summaries to visualize the learning curves in TensorBoard.\n\nTry tweaking some hyperparameters such as the learning rate or the mini-batch size and look at the shape of the learning curve.\n'

In [13]:
from sklearn.datasets import make_moons
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
moons_data = make_moons(n_samples=1000, noise=0.1)
from sklearn.model_selection import train_test_split

n_samples = 1000
X_moons, y_moons = make_moons(n_samples, noise=0.1, random_state=42)
X_moons_with_bias = np.c_[np.ones((n_samples, 1)), X_moons]
y_moons_column_vector = y_moons.reshape(-1, 1)

print(y_moons_column_vector)

test_ratio = 0.2
test_size = int(n_samples * test_ratio)
X_train = X_moons_with_bias[:-test_size]
X_test = X_moons_with_bias[-test_size:]
y_train = y_moons_column_vector[:-test_size]
y_test = y_moons_column_vector[-test_size:]



C:\Users\quanu\Anaconda3\envs\ml\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]


In [14]:
def random_batch(X_train, y_train, batch_size):
    rnd_indices = np.random.randint(0, len(X_train), batch_size)
    X_batch = X_train[rnd_indices]
    y_batch = y_train[rnd_indices]
    return X_batch, y_batch

In [15]:
X_batch, y_batch = random_batch(X_train, y_train, 5)
print(X_batch)
print(y_batch)

[[ 1.          1.57679454 -0.23093592]
 [ 1.          1.90244173  0.28503303]
 [ 1.          0.91050493  0.21417679]
 [ 1.          0.10969484  0.20954502]
 [ 1.          0.61370557 -0.24236929]]
[[1]
 [1]
 [0]
 [1]
 [1]]


In [18]:
reset_graph()

NameError: name 'reset_graph' is not defined

In [19]:
n_inputs  = 2

X = tf.placeholder(tf.float32, shape=(None, n_inputs + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")
theta = tf.Variable(tf.random_uniform([n_inputs + 1, 1], -1.0, 1.0, seed=42), name="theta")
logits = tf.matmul(X, theta, name="logits")
y_proba = 1 / (1 + tf.exp(-logits))

In [20]:
loss = tf.losses.log_loss(y, y_proba) 

In [21]:
learning_rate = 0.01
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

In [22]:
init = tf.global_variables_initializer()

In [24]:
n_epochs = 1000
batch_size = 50
n_batches = int(np.ceil(n_samples / batch_size))

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        for batch_index in range(n_batches):
            X_batch, y_batch = random_batch(X_train, y_train, batch_size)
            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})
        loss_val = loss.eval({X: X_test, y: y_test})
        if epoch % 100 == 0:
            print("Epoch:", epoch, "\tLoss:", loss_val)

    y_proba_val = y_proba.eval(feed_dict={X: X_test, y: y_test})

Epoch: 0 	Loss: 0.87793994
Epoch: 100 	Loss: 0.351537
Epoch: 200 	Loss: 0.31138566
Epoch: 300 	Loss: 0.29480514
Epoch: 400 	Loss: 0.28625453
Epoch: 500 	Loss: 0.281587
Epoch: 600 	Loss: 0.27834377
Epoch: 700 	Loss: 0.27670544
Epoch: 800 	Loss: 0.27587146
Epoch: 900 	Loss: 0.27510464


In [25]:
y_pred = (y_proba_val >= 0.5)

In [26]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_test, y_pred)

0.8627450980392157

In [27]:
recall_score(y_test, y_pred)

0.8888888888888888